spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: auth-service
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=eqa_hr
    username: sa
    password: MyPassword123.@
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

---
# Common configurations for both profiles
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dwabbz@gmail.com
    password: ooug nyba iggp mywc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: dwabbz@gmail.com

server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days