server:
  port: 9002

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/auth/**


        - id: recruitment-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/recruitment/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970